include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - sort_child_properties_last
    - prefer_single_quotes
    - prefer_final_fields
    - use_key_in_widget_constructors
    - prefer_const_constructors
    - prefer_relative_imports
    - unawaited_futures
    - use_build_context_synchronously
    - always_put_required_named_parameters_first
    - prefer_final_locals
    - prefer_is_not_empty
    - avoid_returning_null_for_void
    - type_annotate_public_apis
    - unnecessary_await_in_return
    - use_super_parameters
    - avoid_slow_async_io
    - prefer_collection_literals
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_for_elements_to_map_fromIterable
    - prefer_spread_collections
    - use_is_even_rather_than_modulo