name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Install function package dependencies
        working-directory: functions/translate
        run: |
          dart pub get

      - name: Create CI env file (no secrets committed)
        run: |
          mkdir -p assets
          cat > assets/.env <<'EOF'
          # CI placeholder
          EOF

      - name: Run analyzer (strict)
        run: dart analyze --fatal-infos --fatal-warnings

      - name: Run tests
        run: flutter test --reporter=expanded
